### ISSUE TITLE
Multistate data

### ISSUE THREAD

**Issue by PhyloStar** [PhyloStar/PyBayes#28]
Need a linguistic test set that will allow to test a JC model on multistates.

**Comment by PhyloStar** [comment]
Added Ringe's data. Add morphological data also. Add small datasets from Mixe-Zoque, Chinese, Afrasian, Japanese, Tujia.

**Comment by PhyloStar** [comment]
Have to modify the multistate character data according to the pdf from Ringe. The data is in a bad state.

**Comment by LinguList** [comment]
Here's another dataset:

* https://zenodo.org/record/45233

was used in this publication:

* http://www.jolr.ru/article.php?id=170

Same also on github (see link to zenodo).

**Comment by PhyloStar** [comment]
@LinguList  Do you have any standard cognate datasets in multistate? A unattested concept in a language would be coded as "?". Great. Closing the issue now.

**Comment by LinguList** [comment]
This is not cognate data, but sound change data!

**Comment by PhyloStar** [comment]
Noticed that it is sound change data just now. Looking for cognate data.

**Comment by LinguList** [comment]
Standard data in cognate sets I also have, see here (but not mouch):

* http://dx.doi.org/10.5281/zenodo.50699

and here's the paper:

http://dx.doi.org/10.1093/jole/lzw006

Again step matrices, but they were automatically generated.

**Comment by PhyloStar** [comment]
Added a script to convert List's PIE.csv format files to multistate matrix.

**Comment by PhyloStar** [comment]
Closing issue.
