### ISSUE TITLE
Replicating Hruscka et al.

### ISSUE THREAD

**Issue by PhyloStar** [PhyloStar/PyBayes#32]
Replicating Hruscka et al. is important. This is part of a discussion with @LinguList .

Some features in PyBayes have to enhanced to replicate Hruscka. What are the features?

- What tree prior do Hruscka et al. use? 
- How do they perform dating?
- Do they infer cognates?
- How do they treat gaps in their model?

**Comment by LinguList** [comment]
we can ask Dan, as he shared his source code with me, and they plan to
publish the paper as an alignment algorithm, without the work Pagels
team, as they are two different approaches:

a) alignments (Hruschka's core algo)
b) phylo-inference (the very paper)

**Comment by PhyloStar** [comment]
I reread the paper and ended up more confused. Issues such as age estimation, gap handling, unattested word handling are not dealt clearly.

**Comment by LinguList** [comment]
in the end, we can ask them, write an email to Marc Pagel and also Dan
Hruschka.

**Comment by PhyloStar** [comment]
Ok. Closing then.
