### ISSUE TITLE
F81 model with binary characters

### ISSUE THREAD

**Issue by PhyloStar** [PhyloStar/PyBayes#35]
A faster version of F81 model that computes the transition matrix without numpy routines is required. Separated F81 matrix computation for binary from non-binary characters.

**Comment by LinguList** [comment]
just take this as a rule: NEVER use NUMPY! Unless you only have one big
array and want to go through it. Don't use it for alignments in
linguistics. Numpy slows everything down, if you create many different
arrays. Python lists are the best solution here.

**Comment by PhyloStar** [comment]
Agreed. I only use Numpy for matrix multiplication for computing Felsenstein's Likelihood on a tree. Will open a different issue about faster matrix multiplication.
